package com.krpp.modelo.modelosMapeados;
// Generated 07-dic-2018 20:05:59 by Hibernate Tools 4.3.1



/**
 * Estacionamiento generated by hbm2java
 */
public class EstacionamientoModel  implements java.io.Serializable {


     private int idEstacionamiento;
     private VehiculosModel idVehiculo;
     private LugarModel idLugar;
     private String estado;

    public EstacionamientoModel() {
    }

    public EstacionamientoModel(int idEstacionamiento, VehiculosModel idVehiculo, LugarModel idLugar, String estado) {
       this.idEstacionamiento = idEstacionamiento;
       this.idVehiculo = idVehiculo;
       this.idLugar = idLugar;
       this.estado = estado;
    }
   
    public int getIdEstacionamiento() {
        return this.idEstacionamiento;
    }
    
    public void setIdEstacionamiento(int idEstacionamiento) {
        this.idEstacionamiento = idEstacionamiento;
    }
    public VehiculosModel getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(VehiculosModel idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    public LugarModel getIdLugar() {
        return this.idLugar;
    }
    
    public void setIdLugar(LugarModel idLugar) {
        this.idLugar = idLugar;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


