package com.krpp.modelo.modelosMapeados;
// Generated 07-dic-2018 20:05:59 by Hibernate Tools 4.3.1



/**
 * Lugar generated by hbm2java
 */
public class LugarModel  implements java.io.Serializable {


     private int idLugar;
     private String descripcion;
     private String estado;

    public LugarModel() {
    }

    public LugarModel(int idLugar, String descripcion, String estado) {
       this.idLugar = idLugar;
       this.descripcion = descripcion;
       this.estado = estado;
    }
   
    public int getIdLugar() {
        return this.idLugar;
    }
    
    public void setIdLugar(int idLugar) {
        this.idLugar = idLugar;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


